src/legacy/css/shoutca-st.css
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/14)
=> Remove unused CSS in legacy shoutca-st.css

src/common/footer.css, src/common/index.js, src/index.html, src/legacy/css/shoutca-st.css
This replaces the footer with a new design that's simpler and less
cluttered, with only the most important things.
Maybe the background colour could be different from the navbar's? Feedback welcome.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/13)
=> Replace the footer with a new, simpler, clearer footer

src/manage/cast/links/links.html
Add the ASX link to Links. WIP, don't merge till the Cast update has been pushed.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/24)
=> Add the ASX link

src/app.js, src/common/auth/auth-checker.js, src/common/auth/auth-checker.tests.js, src/common/auth/auth-interceptor.js, src/common/auth/auth-service.js, src/common/auth/auth-service.tests.js, src/common/auth/session.js, src/common/auth/session.tests.js, src/common/navigation-ctrl.js, src/dashboard/dashboard-ctrl.js, src/dashboard/dashboard.html, src/dashboard/index.js, src/index.html, src/manage/extra-services/apps/request-app-ctrl.js, src/manage/services-service.tests.js, webpack.make.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/29)
=> Cleanups (including a cleaner implementation for feature flag)

src/app.js, src/footer.html, src/header-nav.html, src/index.html
This moves the footer and header out of index.html.
**DO NOT MERGE BEFORE #29.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/30)
=> Split index.html

src/manage/extra-services/apps/app-request-ctrl.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/39)
=> Apps: Apply the tab limit only for non-Android apps

src/manage/extra-services/apps/app-request-ctrl.js
This allows users to edit their app to make it a selfHosted request on
their own (as they would be blocked from editing without this change).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/40)
=> Apps: Allow editing self hosted apps regardless of age

src/common/auth/auth-service.js
This fixes a wrong this scope for this.keepAlive() which caused the
interval cancel code not to work properly as it wasn't using the correct
this scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/43)
=> AuthService: Fix broken keep alive cancel code

src/manage/cast/config-service.js, src/manage/cast/streams/streams-ctrl.js, src/manage/cast/streams/streams.html
Add the options under stream with 2 switches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/52)
=> Add antistreamrip and hidelistenercount

src/manage/cast/about/about-ctrl.js, src/manage/cast/about/about-service.js, src/manage/cast/about/about.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/53)
=> Add Cast version to about

src/manage/cast/geolock/geolock-ctrl.js
Delete version check on GeoLock as all versions in production should have it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/55)
=> Delete version check on GeoLock

src/manage/information-pane.html, src/manage/manage-ctrl.js
Add Cast update warning on the service info page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/56)
=> Add Cast update warning

package.json, src/app.js, src/index.html, src/manage/cast/statistics/index.js, src/manage/cast/statistics/statistics-ctrl.js, src/manage/cast/statistics/statistics.css, src/manage/cast/statistics/statistics.html, src/vendor.js
Add a live listener map using the geojson API of Cast
*Please do not merge before the wildcard API in Cast is released*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/54)
=> Add a live listener map

package.json
Fixes issues with children segment reloading, errors in the console, …
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/61)
=> Update to a newer angular-route-segment to fix issues

src/dashboard/dashboard.html
There's not going to be a final release.
I'm not sure why I wrote that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/62)
=> Dashboard: Update feedback message

src/manage/cast/links/links.html
Add extra info to the Links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/63)
=> Cast links

src/manage/cast/connection-info/connection-info-ctrl.js, src/manage/cast/connection-info/connection-info.html
Add Icecast source info to the link page with a toggle swithc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/64)
=> Add Icecast source info

package.json, src/dashboard/dashboard.html, src/feedback/feedback.html, src/header-nav.html, src/manage/extra-services/apps/request-app.html, src/manage/extra-services/apps/view-app-request.html
This should fix Control builds which are deployed with a path that is
not /.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/69)
=> Make all links relative and force them to be rewritten

src/manage/index.js, src/manage/manage-nav.css, src/manage/manage.html
*Needs an ITFrame update to work*
Fixes #48 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/68)
=> Add "Go to Centova Cast" button

src/manage/cast/config-service.js, src/manage/cast/links/links-ctrl.js, src/manage/cast/links/links.html
Add the ability to use your own domain with Cast. 
*Do not merge before ITFrame's PR*
=> Add custom domain option under links

package.json, src/app.js, src/manage/cast/statistics/statistics-ctrl.js, src/manage/cast/statistics/statistics-service.js, src/manage/cast/statistics/statistics.css, src/manage/cast/statistics/statistics.html, src/vendor.js
Add statistics based on the Cast statistics module
=> Add past statistics for Cast

src/manage/cast/connection-info/connection-info.html, src/manage/cast/streams/streams-ctrl.js, src/manage/cast/streams/streams.html
This adds the option to relay a stream on Cast. It will disbale the password so no direct streaming is possible
**Do not merge before next Cast release**
=> Add relay option to streams

src/manage/extra-services/apps/request-app-ctrl.js, src/manage/extra-services/apps/request-app.html
Client-side as we don't really need to do this, but don't want to leave users waiting for too long.
=> [TEMP] Disable iOS app submissions

src/dj/continuous/clocks/clocks-ctrl.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/83)
=> fix clocks save check

package-lock.json, src/manage/extra-services/player/player-ctrl.js, src/manage/extra-services/player/player-service.js, src/manage/extra-services/player/player.html
See https://github.com/innovate-technologies/itframe/pull/128
=> Add upload nocover box on player

package.json, src/app.js, src/dj/continuous/intervals/intervals-ctrl.js, src/dj/continuous/intervals/intervals.css, src/dj/continuous/intervals/intervals.html, src/vendor.js
WIP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/innovate-technologies/control/84)
=> Add more intervals options
